### ISSUE TITLE
Error: Module version mismatch. Expected 13, got 11

### ISSUE THREAD

**Issue by wangbinlml** [3rd-Eden/node-hashring#26]
i use node version is v.11.10:
When running my node.js program I got the following error;

/home/liubin/workspace_bak/core_mm/node_modules/hashring/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module version mismatch. Expected 13, got 11.
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at bindings (/home/liubin/workspace_bak/core_mm/node_modules/hashring/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/liubin/workspace_bak/core_mm/node_modules/hashring/index.js:3:36)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)

please help me!!!

**Comment by 3rd-Eden** [comment]
You didn't re-install your node modules after upgrading to 0.11. So the binary is build against the old node version.
